
package javaapplication2;

import java.util.ArrayList;
import java.sql.*;  
import javax.swing.table.DefaultTableModel;


public class Premium_list extends javax.swing.JPanel {
Anasayfa ana;
static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DOMAIN_NAME = "localhost";
    static final String DB_NAME = "muzik_dosyam";
    static final String DB_URL = "jdbc:mysql://" + DOMAIN_NAME + "/" + DB_NAME;
    
     //  Database credentials
     static final String USER = "root";//MySQL connection'ın değerlerini değiştirdiyseniz, burayıda ona göre değiştirmelisiniz.
        static final String PASS = "cZ.;dIS1g";//MySQL connection'ın değerlerini değiştirdiyseniz, burayıda ona göre değiştirmelisiniz.
        
    public Anasayfa getAna() {
        return ana;
    }

    public void setAna(Anasayfa ana) {
        this.ana = ana;
    }
   
    public Premium_list() {
        initComponents();
        showList();
        
        
    }
public ArrayList<Onelist> useList(){
    ArrayList<Onelist> userList = new ArrayList<>();
     Connection conn = null;
       PreparedStatement psmt = null;
    try{
           
            Class.forName("com.mysql.cj.jdbc.Driver");  
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
           String sql="SELECT Kullanici_adi FROM kullanici  WHERE Abonelik_turu = 'Premium'";
            psmt = conn.prepareStatement(sql);
            ResultSet rs = psmt.executeQuery();// SELECT li sql querylerinde kullanıyoruz.
            Onelist olist;
           while(rs.next()){
     olist = new Onelist(rs.getString(1));
            userList.add(olist);
            }
            
    
        } catch (SQLException se) {
            //Handle errors for JDBC
            se.printStackTrace();
        } catch (Exception e) {
            //Handle errors for Class.forName
            e.printStackTrace();
        }
    return userList;
    }

 public void showList(){
 ArrayList<Onelist> list = useList();
  DefaultTableModel a = (DefaultTableModel) jTable1.getModel();
  Object[] row = new Object[1];
  int imax = list.size();
     for (int i = 0; i < imax; i++) {
         
         row[0] = list.get(i).getA2();
         
       a.addRow(row);
     }  
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("GERI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Premium Kullanicilar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Profiline git");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ana.anasayfagoster();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if(jTable1.isRowSelected(jTable1.getSelectedRow())){
        String kullaniciadi = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        
        Premiumprofil p = new Premiumprofil();
        
        p.kullaniciadi = kullaniciadi;
        
        jButton1.setVisible(false);
        jButton3.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
        
        p.setBounds(0,0, 1006, 623);
        add(p);
        p.setVisible(true);
        p.setP(this);
        p.combo = 1;
        p.showList();
        p.combo = 2;
        p.showList();
        p.combo = 3;
        p.showList();
          repaint();}
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
public void Premium_listgoster(){

jButton1.setVisible(true);
jButton3.setVisible(true);
jScrollPane1.setVisible(true);
jTable1.setVisible(true);
}
public class Onelist{
String a2;
    public Onelist(String a2){
   this.a2 = a2;
    }
        public String getA2() {
            return a2;
        }
}

}
